In [1]:
import numpy as np

In [5]:
td_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [8]:
zeros = np.zeros(5)

In [9]:
print(zeros)

[0. 0. 0. 0. 0.]


In [19]:
arr = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])

In [21]:
print(arr.nbytes)

80


In [24]:
print(arr[1, :])

[ 6  7  8  9 10]


In [25]:
print(arr[:, 1])

[2 7]


In [26]:
print(arr[0:2, 0:2])

[[1 2]
 [6 7]]


In [27]:
print(arr.T)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [7]:
students = [[50, 60, 70], [80, 90, 100 ], [78, 98, 99]] 

print(students)

[[50, 60, 70], [80, 90, 100], [78, 98, 99]]


In [8]:
print(np.mean(students, axis=1))

[60.         90.         91.66666667]


In [13]:
# Find best student based on average marks
# give me index of best student and his average marks
avg_marks = np.mean(students, axis=1)
print(avg_marks)
best_student_index = np.argmax(avg_marks)
print(best_student_index)
best_student_avg_marks = avg_marks[best_student_index]
print(f"Best student index: {best_student_index}, Average marks: {best_student_avg_marks}")


[60.         90.         91.66666667]
2
Best student index: 2, Average marks: 91.66666666666667


In [24]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])
arr3 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(np.add(arr1, arr2), arr3)

print(newarr)

[50 53 56 59 62 65]


In [25]:
num1 = 4
num2 = 6

x = np.gcd(num1, num2)

print(x)

2


In [ ]:
x = np.random.exponential(scale=2, size=(2, 3))

print(x)

pip install matplotlib seaborn

[[2.25173529 8.16431541 0.77042521]
 [0.53894397 3.0677995  1.80359889]]


In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.displot(np.random.exponential(size=1000), kind="kde")

plt.show()